// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9LYxhIAO1ykF5QRjBbFy-KlRI1XLkcU',
    appId: '1:496198811122:web:d2b53b9bf0f1e1531eff6b',
    messagingSenderId: '496198811122',
    projectId: 'ecommernceapp-33a74',
    authDomain: 'ecommernceapp-33a74.firebaseapp.com',
    storageBucket: 'ecommernceapp-33a74.firebasestorage.app',
    measurementId: 'G-8JQBCHTFNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFwERaGSpvx899ts2YdaR7r636k3Leu4',
    appId: '1:496198811122:android:36d8f476e29d32f31eff6b',
    messagingSenderId: '496198811122',
    projectId: 'ecommernceapp-33a74',
    storageBucket: 'ecommernceapp-33a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcrsy471KJWEm9zag8BQkVuO7zQGOLpI',
    appId: '1:496198811122:ios:d9241e78c17bcd6d1eff6b',
    messagingSenderId: '496198811122',
    projectId: 'ecommernceapp-33a74',
    storageBucket: 'ecommernceapp-33a74.firebasestorage.app',
    androidClientId: '496198811122-q37vnq8f8ppvlnu5bgnlklhmihhesmd3.apps.googleusercontent.com',
    iosClientId: '496198811122-ik7s359bo67kcigjsd6qvqdqer1oq49b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tShop',
  );

}